# Generated by Django 4.2 on 2023-04-07 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_team_members'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strategy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('definition', models.TextField()),
                ('price', models.IntegerField()),
                ('max_clients', models.IntegerField()),
                ('max_leads', models.IntegerField()),
            ],
        ),
    ]
