# Generated by Django 4.2 on 2023-04-07 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0003_strategy'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='strategy',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='team.strategy'),
            preserve_default=False,
        ),
    ]
