# Generated by Django 4.2 on 2023-04-07 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmclient', '0002_client_team'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ('name',)},
        ),
    ]
