# Generated by Django 4.2 on 2023-04-09 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crmclient', '0005_clientfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientfile',
            old_name='lead',
            new_name='client',
        ),
    ]
