# Generated by Django 4.2 on 2023-04-07 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lead', '0004_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='contect',
            new_name='content',
        ),
    ]
